### ISSUE TITLE
Include of non-modular header inside framework module 'ctermbox'

### ISSUE THREAD

**Issue by dropbear32** [dduan/Termbox#4]
I've added this repository as a Swift package and generated a `.xcodeproj` file to use. When compiling via Terminal, this works fine, but when compiling in Xcode, I receive the following error:
<img width="1392" alt="Screen Shot 2019-09-12 at 8 48 07 AM" src="https://user-images.githubusercontent.com/17181723/64799675-10e87500-d53a-11e9-80fe-41fde1c23e5c.png">
I'm not versed in mixing C and Swift, so I'm not sure how to resolve this. I've attempted setting "Allow Non-modular Includes In Framework Modules" in ctermbox's build settings to "Yes", but that doesn't help anything.

**Comment by dduan** [comment]
This is fixed in `main` and therefore the next release.
